iio: jesd204: axi_adxcvr: Support for physical layer PRBS
This commit adds support for physical layer PRBS Generation and Checking.
The new feature is supported starting with HDL core version 17.02.a
Depending on the direction AXI-ADXCVR-RX or AXI-ADXCVR-TX different new
sysfs files are supported which are explained below.

axi-adxcvr-rx:
prbs_select
  Writing selects the PRBS type. (accepted values depend on the GT
  architecture) Reading returns the selected type.
    0: PRBS_DISABLE
    7: PRBS7
    9: PRBS9
    15: PRBS15
    23: PRBS23
    31: PRBS31

prbs_status:
  Reading returns a status string. Values are:
    unlocked: The PRBS is unlocked
    valid: The PRBS is locked and no errors are detected
    error: The PRBS has locked but errors were detected

  These conditions are sticky and can be cleared by writing 1 to
  prbs_counter_reset

prbs_error_counters:
  Reading returns a string with error counts for each physical
  JESD204 lane.

prbs_counter_reset:
  Writing 1 will clear the prbs_status and reset the prbs_error_counters

axi-adxcvr-tx:
prbs_select
  Writing selects the PRBS type. (accepted values depend on the GT
  architecture) Reading returns the selected type.
    0: PRBS_DISABLE
    7: PRBS7
    9: PRBS9
    15: PRBS15
    23: PRBS23
    31: PRBS31

prbs_error_inject:
  Writing 1 injects a series of errors´(used for testing)

Signed-off-by: Michael Hennerich <michael.hennerich@analog.com>
(cherry picked from commit d7dfd2fd789a88fed785f59b348c6a96199ec36f)