iio: beamformer: adar1000: Fix a build failure
The compiler is unhappy when the driver is configured as a module:

	In file included from drivers/iio/beamformer/adar1000.c:9:
	include/linux/module.h:244:1: error: expected ‘,’ or ‘;’ before ‘extern’
	  244 | extern typeof(name) __mod_##type##__##name##_device_table               \
	      | ^~~~~~
	drivers/iio/beamformer/adar1000.c:2639:1: note: in expansion of macro ‘MODULE_DEVICE_TABLE’
	 2639 | MODULE_DEVICE_TABLE(spi, adar1000_id_table);
	      | ^~~~~~~~~~~~~~~~~~~

and when the ; is added dies again with:

	In file included from drivers/iio/beamformer/adar1000.c:9:
	drivers/iio/beamformer/adar1000.c:2639:26: error: ‘adar1000_id_table’ undeclared here (not in a function); did you mean ‘adar1000_read_enable’?
	 2639 | MODULE_DEVICE_TABLE(spi, adar1000_id_table);
	      |                          ^~~~~~~~~~~~~~~~~
	include/linux/module.h:244:15: note: in definition of macro ‘MODULE_DEVICE_TABLE’
	  244 | extern typeof(name) __mod_##type##__##name##_device_table               \
	      |               ^~~~
	include/linux/module.h:244:21: error: ‘__mod_spi__adar1000_id_table_device_table’ aliased to undefined symbol ‘adar1000_id_table’
	  244 | extern typeof(name) __mod_##type##__##name##_device_table               \
	      |                     ^~~~~~
	drivers/iio/beamformer/adar1000.c:2639:1: note: in expansion of macro ‘MODULE_DEVICE_TABLE’
	 2639 | MODULE_DEVICE_TABLE(spi, adar1000_id_table);
	      | ^~~~~~~~~~~~~~~~~~~

Fixes: 7e7216d72564 ("iio: beamformer: adar1000: add spi_device_id table")
Signed-off-by: Uwe Kleine-König <u.kleine-koenig@baylibre.com>