drivers: mathworks: fix functions type for vm fault
On ARM, this reports as a compiler warning/error:
```
drivers/misc/mathworks/mathworks_ip_common.c:218:14: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
     .fault = mathworks_ip_mmap_fault,

drivers/misc/mathworks/mw_stream_channel.c:785:23: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
     .fault          = mwadma_mmap_fault,
```

It was omitted during merge.
This patch updates the function type to the new required format.

Signed-off-by: Alexandru Ardelean <alexandru.ardelean@analog.com>