LF-6810-03: media: Samsung CSI2: fix build error due to API renamed
Fix Samsung MIPI CSI2 driver build error due to API renamed in bellow commit:
drivers/staging/media/imx/imx8-mipi-csi2-sam.c:594:46:
error: implicit declaration of function ‘media_entity_remote_pad’; did you mean ‘media_entity_remove_links’? [-Werror=implicit-function-declaration]

(b2e44430b634 media: mc-entity: Rename media_entity_remote_pad() to
 media_pad_remote_pad_first())

Signed-off-by: Guoniu.zhou <guoniu.zhou@nxp.com>
Reviewed-by: Robby Cai <Robby.Cai@nxp.com>