iio: logic: axi-aion-trig: Select REGMAP_MMIO
Fixes:
ERROR: modpost: "__devm_regmap_init_mmio_clk" [drivers/iio/logic/axi-aion-trig.ko] undefined!

Fixes: ec391b42b9dc ("iio: logic: axi-aion-trig: New driver for the AXI AION HDL IP Core")

Signed-off-by: Michael Hennerich <michael.hennerich@analog.com>