x86/purgatory: Compile purgatory with -D__NO_FORTIFY
A subsequent patch will add #include <linux/string.h> to <crypto/sha2.h>
to use memzero_explicit() there. This will introduce a conflict with the
purgatory code: purgatory.c includes both, the <crypto/sha2.h> header and
the arch/x86/boot/string.h header. The latter provides its own prototypes
for a lot of string functions which clash with the fortified macros
from <linux/string.h>, causing the compiler to emit errors like this:

 In file included from .../linux/include/linux/string.h:383,
                  from .../linux/include/crypto/sha2.h:10,
                  from .../linux/arch/x86/purgatory/purgatory.c:14:
 .../linux/include/linux/fortify-string.h:576:63: error: expected identifier or ‘(’ before ‘{’ token
   576 |                              p_size_field, q_size_field, op) ({         \
       |                                                               ^
 .../linux/include/linux/fortify-string.h:644:27: note: in expansion of macro ‘__fortify_memcpy_chk’
   644 | #define memmove(p, q, s)  __fortify_memcpy_chk(p, q, s,                 \
       |                           ^~~~~~~~~~~~~~~~~~~~
 .../linux/arch/x86/purgatory/../boot/string.h:11:7: note: in expansion of macro ‘memmove’
    11 | void *memmove(void *dst, const void *src, size_t len);
       |       ^~~~~~~
 .../linux/include/linux/fortify-string.h:208:9: error: expected identifier or ‘(’ before ‘__builtin_choose_expr’
   208 |         __builtin_choose_expr(__is_constexpr(__builtin_strlen(p)),      \
       |         ^~~~~~~~~~~~~~~~~~~~~
 ./linux/arch/x86/purgatory/../boot/string.h:23:15: note: in expansion of macro ‘strlen’
    23 | extern size_t strlen(const char *s);
       |               ^~~~~~

To avoid the problem, let's compile the code in the purgatory with
-D__NO_FORTIFY, so <linux/string.h> can properly be included from
headers like <crypto/sha2.h> in the purgatory, too.

Signed-off-by: Thomas Huth <thuth@redhat.com>
Link: https://patch.msgid.link/20260916095022.604354-11-thuth@redhat.com
Signed-off-by: Eric Biggers <ebiggers@kernel.org>