iio: adc: ad7768: depends on CF_AXI_ADC
The driver uses axiadc_write(), provided by symbol CF_AXI_ADC.
Solves:
  ERROR: modpost: "axiadc_write" [drivers/iio/adc/ad7768.ko] undefined!

Signed-off-by: Jorge Marques <jorge.marques@analog.com>
(cherry picked from commit 16f56c138e1706b4073d085ff3d1591fb83e7615)