build,travis: use FETCH_HEAD when sync-ing
Because on Travis-CI, the repo is cloned with 50 commits-depth, and
git-fetch is also done at around 50 commits-depth, and because (when doing
git-fetch) we don't keep a local reference to the fetch, we need to use
FETCH_HEAD.

Otherwise the error is something like:
```
From github.com:analogdevicesinc/linux
 * branch                xcomm_zynq -> FETCH_HEAD
error: pathspec 'origin/xcomm_zynq' did not match any file(s) known to git.
The command "./ci/travis/run-build.sh" exited with 1.
```

A reason this fails, is related to commit
c76a5209408fc37753a3d2f21dcf9f35078b7059 ("build: use detached versions of
the remote branches"). We still want detached versions of the git-fetch-ed
stuff, and the only reference there exists when doing a git-fetch is
`FETCH_HEAD`.

Tested locally, with a cloned-repo of 50 commits (just like Travis-CI
does). This wasn't caught earlier, because it was tested on a repo that
has many local git-refs.

Signed-off-by: Alexandru Ardelean <alexandru.ardelean@analog.com>
(cherry picked from commit 9952a383ecd77acd1468c35ad55282da0f7cf581)