iio: adc: ad9088: select ADI_AXI_HSCI driver dependency
The AD9088 driver uses the HSCI (High Speed Configuration Interface)
functions from the ADI AXI HSCI driver. Add the Kconfig select to
ensure the HSCI driver is built when AD9088 is enabled.

This fixes linker errors when AD9088 is enabled without HSCI:

  undefined reference to `axi_hsci_writem'
  undefined reference to `axi_hsci_readm'
  undefined reference to `axi_hsci_alink_tbl_get'
  undefined reference to `axi_hsci_auto_linkup'
  undefined reference to `axi_hsci_manual_linkup'
  undefined reference to `devm_axi_hsci_get_optional'

Fixes: 832491249ce5 ("iio: adc: apollo: Initial support for AD9084")

Signed-off-by: Michael Hennerich <michael.hennerich@analog.com>