CI: install GitPython for checkpatch
Without GitPython installed, the checkpatch script prints an error
when trying to run the spdxcheck.py script.

Traceback (most recent call last):
  File "scripts/spdxcheck.py", line 10, in <module>
    import git
ModuleNotFoundError: No module named 'git'

Although it is not fatal, just install the python package to get
rid of it.

Signed-off-by: Cosmin Tanislav <cosmin.tanislav@analog.com>
(cherry picked from commit ebcb3f94a875e4b7d8881a25900cc157a7f9d656)