ci: install dependencies for 'build_checkpatch()'
Install ply module. This is needed by checkpatch, otherwise we keep
seeing:

"
Traceback (most recent call last):
  File "scripts/spdxcheck.py", line 6, in <module>
    from ply import lex, yacc
ModuleNotFoundError: No module named 'ply'
Traceback (most recent call last):
  File "scripts/spdxcheck.py", line 6, in <module>
    from ply import lex, yacc
ModuleNotFoundError: No module named 'ply'
Traceback (most recent call last):
  File "scripts/spdxcheck.py", line 6, in <module>
    from ply import lex, yacc
ModuleNotFoundError: No module named 'ply'
"

Signed-off-by: Nuno Sá <nuno.sa@analog.com>
(cherry picked from commit 13b010367b1c3808c5c3e9d50f9a39355624c297)