drivers: mathworks: fix sprintf argument warning
In function mw_stream_chan_show the warning is:
'''
drivers/misc/mathworks/mw_stream_channel.c:1050:25: error:
format ‘%llu’ expects argument of type ‘long long unsigned int’,
but argument 3 has type ‘long int’ [-Werror=format=]
'''

Signed-off-by: Alexandru Tachici <alexandru.tachici@analog.com>
(cherry picked from commit 69a8743b524d71ff71c272b1373500e2240ac1ea)