MA-23228 drm/imx: dpu: kms: Fix build error
error log:

drivers/gpu/drm/imx/dpu/dpu-kms.c:196:6: error: variable 's0_n' set but not used [-Werror,-Wunused-but-set-variable]
  196 |         int s0_n = 0, s1_n = 0;
      |             ^
1 error generated.

The variable 's0_n' is set but never used, which causes a
-Wunused-but-set-variable warning during compilation.

Since 's0_n' is not used in any logic, this patch removes its
declaration and assignments to fix the warning.

Change-Id: I8b6995579a8c73dfa9b42d9568d4c60b8bc88221
Signed-off-by: Zhipeng Wang <zhipeng.wang_1@nxp.com>
Reviewed-by: Liu Ying <victor.liu@nxp.com>