Revert "drivers: iio: adc: xilinx-ams: Add over temperature interrupts"
This reverts commit f6e3323a5d71d1f893ed20fdecc6b21d784d6683.

The commit is clearly bogus and does not even compile with clang 18.1.8.
Hence, let's revert it and wait until AMD fixes it (unless we need it
first). Here are the compiler complains (warnings included):

././include/linux/compiler_types.h:357:45: error: call to '__compiletime_assert_273' declared with attribute error: FIELD_GET: mask is zero
  357 |         _compiletime_assert(condition, msg, __compiletime_assert_, __COUNTER__)

  CALL    scripts/checksyscalls.sh
  CC      drivers/iio/adc/xilinx-ams.o
drivers/iio/adc/xilinx-ams.c: In function 'ams_update_alarm':
drivers/iio/adc/xilinx-ams.c:416:51: warning: left shift count >= width of type [-Wshift-count-overflow]
  416 |                              (AMS_ISR1_ALARM_MASK << AMS_ISR1_ALARM_SHIFT)),
      |                                                   ^~
In file included from ./include/linux/bits.h:6,
                 from drivers/iio/adc/xilinx-ams.c:11:
drivers/iio/adc/xilinx-ams.c: In function 'ams_get_alarm_mask':
./include/vdso/bits.h:7:40: warning: left shift count >= width of type [-Wshift-count-overflow]
    7 | #define BIT(nr)                 (UL(1) << (nr))
      |                                        ^~
drivers/iio/adc/xilinx-ams.c:921:24: note: in expansion of macro 'BIT'
  921 |                 return BIT(AMS_ALARM_BIT_TEMP_OT_REMOTE);
      |                        ^~~
drivers/iio/adc/xilinx-ams.c: In function 'ams_irq':
drivers/iio/adc/xilinx-ams.c:1129:42: warning: left shift count >= width of type [-Wshift-count-overflow]
 1129 |                     (AMS_ISR1_ALARM_MASK << AMS_ISR1_ALARM_SHIFT)) |

Signed-off-by: Nuno Sa <nuno.sa@analog.com>