MA-22385 neutron: Fix variable initialization causing build error
error log:
drivers/staging/neutron/neutron_inference.c:348:3: error: expected expression
struct neutron_uapi_result_status uapi;

Change-Id: I8e33bd706f65660532e3ec650315dff369bcf055
Signed-off-by: Zhipeng Wang <zhipeng.wang_1@nxp.com>