ci,build: don't cherry-pick commit if already up-to-date
This only fixes the cases when doing branch-sync with master locally.

`git cherry-pick` fails with:
```
Failed to cherry-pick commits '<commit>..adi/master'
error: empty commit set passed
fatal: cherry-pick failed
```
when trying to cherry-pick something that was already cherry-picked.

In this case, the commit was already cherry-picked, so, doing
`git cherry-pick <commit>..adi/master` will error out.

Signed-off-by: Alexandru Ardelean <alexandru.ardelean@analog.com>
(cherry picked from commit 844406963582790931062907a1f6b27aec9a13ae)