Revert "vdso/gettimeofday: Assert that the clockid fits into the u32 bitmask"
This reverts commit ca46a07c4b68246c4e400ce3649ab7228a878d8f due to.

/tmp/next/build/lib/vdso/gettimeofday.c: In function '__cvdso_clock_gettime_common':
/tmp/next/build/lib/vdso/gettimeofday.c:288:31: error: implicit declaration of function 'BITS_PER_TYPE'; did you mean 'BITS_PER_LONG'? [-Wimplicit-function-declaration]
  288 |         BUILD_BUG_ON(clock >= BITS_PER_TYPE(msk));
      |                               ^~~~~~~~~~~~~
/tmp/next/build/include/linux/compiler_types.h:682:23: note: in definition of macro '__compiletime_assert'
  682 |                 if (!(condition))                                       \
      |                       ^~~~~~~~~
/tmp/next/build/include/linux/compiler_types.h:702:9: note: in expansion of macro '_compiletime_assert'
  702 |         _compiletime_assert(condition, msg, __compiletime_assert_, __COUNTER__)
      |         ^~~~~~~~~~~~~~~~~~~
/tmp/next/build/include/linux/build_bug.h:40:37: note: in expansion of macro 'compiletime_assert'
   40 | #define BUILD_BUG_ON_MSG(cond, msg) compiletime_assert(!(cond), msg)
      |                                     ^~~~~~~~~~~~~~~~~~
/tmp/next/build/include/linux/build_bug.h:51:9: note: in expansion of macro 'BUILD_BUG_ON_MSG'
   51 |         BUILD_BUG_ON_MSG(condition, "BUILD_BUG_ON failed: " #condition)
      |         ^~~~~~~~~~~~~~~~
/tmp/next/build/lib/vdso/gettimeofday.c:288:9: note: in expansion of macro 'BUILD_BUG_ON'
  288 |         BUILD_BUG_ON(clock >= BITS_PER_TYPE(msk));
      |         ^~~~~~~~~~~~

Signed-off-by: Mark Brown <broonie@kernel.org>