clk: clk-xlnx-clock-wizard: fix 64bit division on 32bit archs
Use the proper APIs to do 64bit division on 32bit architectures.
Otherwise we get:

"undefined reference to `__aeabi_uldivmod'"

Fixes: bf7387ee9a75c ("clocking-wizard: Support higher frequency accuracy")
Signed-off-by: Nuno Sá <nuno.sa@analog.com>
(cherry picked from commit de10536d25eea1238ccfb6f266c082e7fcc7b2ab)