iio: adc: ad9081: fix implicit fall-throughs
It looks like that switch statement is missing some break statements.
The newer kernel branch caught this via build:
```
 CC      drivers/iio/adc/ad9081.o
drivers/iio/adc/ad9081.c: In function 'ad9081_calc_lanerate':
drivers/iio/adc/ad9081.c:214:14: error: this statement may fall through [-Werror=implicit-fallthrough=]
  214 |   encoding_d = 64;
      |   ~~~~~~~~~~~^~~~
drivers/iio/adc/ad9081.c:215:2: note: here
  215 |  default:
      |  ^~~~~~~
  CC      net/ipv4/metrics.o
```

Signed-off-by: Alexandru Ardelean <alexandru.ardelean@analog.com>
(cherry picked from commit 2392f699012e8c116ea171c39292f5dd82c8e1c3)