drm: adi_axi_hdmi: fix compiler warning (unused var)
Warning is:
```
drivers/gpu/drm/adi_axi_hdmi/axi_hdmi_crtc.c:44:28: error: unused variable ‘vdma_config’ [-Werror=unused-variable]
  struct xilinx_vdma_config vdma_config;
```

This is because the `CONFIG_XILINX_DMA` Kconfig symbol isn't enabled, so
the variable appears unused, causing a compiler warning.

Signed-off-by: Alexandru Ardelean <alexandru.ardelean@analog.com>
(cherry picked from commit b02a1a1fee2dee7aee17bef5c54e2beb9a9b1ea3)