tpm: remove extraneous #ifdef
Changing to DEFINE_SIMPLE_DEV_PM_OPS() broke here because the
tpm_inf_resume() function is hidden in an #ifdef:

drivers/char/tpm/tpm_infineon.c:615:61: error: 'tpm_inf_resume' undeclared here (not in a function); did you mean 'tpm_pm_resume'?
  615 | static DEFINE_SIMPLE_DEV_PM_OPS(tpm_inf_pm, tpm_pm_suspend, tpm_inf_resume);
      |                                                             ^~~~~~~~~~~~~~

Remove the #ifdef check.

Fixes: 2249200ee420 ("tpm: use DEFINE_SIMPLE_DEV_PM_OPS and pm_sleep_ptr()")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Tested-by: Uwe Kleine-König <u.kleine-koenig@baylibre.com>
Link: https://lore.kernel.org/r/20260915201305.3529682-1-arnd@kernel.org
Signed-off-by: Jarkko Sakkinen <jarkko@kernel.org>