iio: adc: ad9081: Remove "adi_utils.h" include
Not available but not used either.

Fixes:
   fatal error: adi_utils.h: No such file or directory

Signed-off-by: Dragos Bogdan <dragos.bogdan@analog.com>
(cherry picked from commit 5ec13a594e81a28690ba61d11387b61bb7daab85)