iio: adc: ad9081: Fix use of uninitialized variable
drivers/iio/adc/ad9081.c:1596:53: error: 'tx_lane_rate_kbps' may be used uninitialized in this function [-Werror=maybe-uninitialized]
 1596 |  if ((phy->jesd_tx_link.jesd_param.jesd_jesdv == 2) &&
      |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
 1597 |   (tx_lane_rate_kbps > 16230000UL)) {

Signed-off-by: Michael Hennerich <michael.hennerich@analog.com>
(cherry picked from commit 43e276fec00faa319cc37e402a9d054a9f973a4d)