media: xilinx: xilinx-hdmirxss: fix 64bit division on 32bit archs
Use the proper APIs to do 64bit division on 32bit architectures.
Otherwise we get:

"undefined reference to `__aeabi_uldivmod'"

Fixes: e6ff9941b32da ("v4l: xilinx: hdmirx: Add FRL support to VTD interrupt handler")
Signed-off-by: Nuno Sá <nuno.sa@analog.com>
(cherry picked from commit 9278a7cb3140c1955931190671bc169abb332886)