Revert "iio: adc: re-organize Makefile in alphabetical order"
This reverts commit a9b0a536a5e62b923b6cf8daa6e1dd6bd1c679e5.

This patch has some strange side effect. It causes muliple error messages during
kernel start. And it also causes that the cf_axi_dds driver is loaded after
the cf_axi_adc_drv which in return is causing some of the rate configuration to be
overwritten.

Without this patch:
ad9361 spi32766.0: ad9361_probe : AD936x Rev 2 successfully initialized
cf_axi_dds 79024000.cf-ad9361-dds-core-lpc: Analog Devices CF_AXI_DDS_DDS MASTER (9.00.b) at 0x79024000 mapped to 0xe083e000, probed DDS AD9364
cf_axi_adc 79020000.cf-ad9361-lpc: ADI AIM (10.00.b) at 0x79020000 mapped to 0xe0938000, probed ADC AD9364 as MASTER

With this patch:
ad9361 spi32766.0: ad9361_probe : AD936x Rev 2 successfully initialized
Error: Driver 'admc_drv' is already registered, aborting...
Error: Driver 'admc_drv' is already registered, aborting...
Error: Driver 'admc_drv' is already registered, aborting...
cf_axi_adc_drv 79020000.cf-ad9361-lpc: ADI AIM (10.00.b) at 0x79020000 mapped to 0xe0938000, probed ADC AD9364 as MASTER
cf_axi_dds 79024000.cf-ad9361-dds-core-lpc: Analog Devices CF_AXI_DDS_DDS MASTER (9.00.b) at 0x79024000 mapped to 0xe083e000, probed DDS AD9364

Signed-off-by: Michael Hennerich <michael.hennerich@analog.com>