net: sdk_dpaa: fix build issue of __assign_str
API changed since the commit
2c92ca849fcc ("tracing/treewide: Remove second parameter of __assign_str()")

../drivers/net/ethernet/freescale/sdk_dpaa/./dpaa_eth_trace.h: In function ‘perf_trace_dpaa_eth_fd’:
../drivers/net/ethernet/freescale/sdk_dpaa/./dpaa_eth_trace.h:88:17: error: ‘__assign_str’ undeclared (first use in this function)
   88 |                 __assign_str(name, netdev->name);
      |                 ^~~~~~~~~~~~

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Vladimir Oltean <vladimir.oltean@nxp.com>