LF-13827-6 net: ppfe: update the usage of eventfd_signal
Cope with the API change since the commit
1808acc4fab2 ("eventfd: simplify eventfd_signal()")

Otherwise will meet the following build error:
drivers/staging/fsl_ppfe/pfe_cdev.c: In function ‘hif_us_isr’:
drivers/staging/fsl_ppfe/pfe_cdev.c:112:17: error: too many arguments to function ‘eventfd_signal’
  112 |                 eventfd_signal(trigger, 1);
      |                 ^~~~~~~~~~~~~~

Reviewed-by: Wei Fang <wei.fang@nxp.com>
Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>