ASoC: fsl: mpc5200: gate AC97 driver on PPC_MPC52xx
The MPC5200 PSC AC97 driver only applies to the MPC52xx family of
SoCs, but only depended on PPC_BESTCOMM. Restrict the driver to
MPC52xx platforms so it is not offered (and does not fail to build)
on other bestcomm-based machines.

Fixes the following linking error:

ERROR: modpost: sound/soc/fsl/mpc5200_psc_ac97.ko: symbol 'mpc5200_psc_ac97_gpio_reset' undefined!

Assisted-by: LLM
Signed-off-by: Rosen Penev <rosenp@gmail.com>
Link: https://patch.msgid.link/20260916220453.260472-1-rosenp@gmail.com
Signed-off-by: Mark Brown <broonie@kernel.org>