clkk: clk-xlnx-clock-wizard-v: fix 64bit division on 32bit archs
Use the proper APIs to do 64bit division on 32bit architectures.
Otherwise we get:

"undefined reference to `__aeabi_uldivmod'"

Fixes: c1e2db426dc72 ("clocking-wizard: Support higher frequency accuracy")
Signed-off-by: Nuno Sá <nuno.sa@analog.com>