navassa: fix ISO C90 compiler warning
drivers/iio/adc/navassa/devices/adrv9001/public/src/adi_adrv9001_profileutil.c: In function ‘adi_adrv9001_profileutil_Parse’:
drivers/iio/adc/navassa/devices/adrv9001/public/src/adi_adrv9001_profileutil.c:47:5: error: ISO C90 forbids array ‘parsingBuffer’ whose size cannot be evaluated [-Werror=vla]
   47 |     char parsingBuffer[ADI_ADRV9001_TOKEN_MAX_LENGTH]; /* This buffer only needs to hold a stringified number like '123.4567'. */
      |     ^~~~

Signed-off-by: Alexandru Ardelean <alexandru.ardelean@analog.com>
(cherry picked from commit b3e8205479f0d1ce5b29ebfae16cad47a06f78d2)