drm: xlnx: zynqmp_disp: Fix unused variable warning
Warning is:
'''
drivers/gpu/drm/xlnx/zynqmp_disp.c: In function ‘zynqmp_disp_plane_mode_set’:
drivers/gpu/drm/xlnx/zynqmp_disp.c:2478:29: error: unused variable ‘format_name’
 [-Werror=unused-variable]
  struct drm_format_name_buf format_name;
'''

Signed-off-by: Alexandru Tachici <alexandru.tachici@analog.com>
(cherry picked from commit fe5c9eb97583844d28aa01a1f513fe39d37e41d6)