LF-9969 media: hdmirx: fix build error due to api change
In file included from ../drivers/staging/media/imx/hdmirx/cdns-hdmirx-hdcp.c:10:
../drivers/staging/media/imx/hdmirx/cdns-mhdp-hdmirx.h:312:34: error: field ¡®asd¡¯ has incomplete type
  312 |         struct v4l2_async_subdev asd;
      |                                  ^~~
make[8]: *** [../scripts/Makefile.build:243: drivers/staging/media/imx/hdmirx/cdns-hdmirx-hdcp.o] Error 1
make[8]: *** Waiting for unfinished jobs....
In file included from ../drivers/staging/media/imx/hdmirx/cdns-mhdp-hdmirx.c:13:
../drivers/staging/media/imx/hdmirx/cdns-mhdp-hdmirx.h:312:34: error: field ¡®asd¡¯ has incomplete type
  312 |         struct v4l2_async_subdev asd;
      |                                  ^~~
make[8]: *** [../scripts/Makefile.build:243: drivers/staging/media/imx/hdmirx/cdns-mhdp-hdmirx.o] Error 1
In file included from ../drivers/staging/media/imx/hdmirx/cdns-hdmirx-phy.h:15,
                 from ../drivers/staging/media/imx/hdmirx/cdns-hdmirx-phy.c:11:
../drivers/staging/media/imx/hdmirx/cdns-mhdp-hdmirx.h:312:34: error: field ¡®asd¡¯ has incomplete type
  312 |         struct v4l2_async_subdev asd;
      |                                  ^~~

caused by
commit adb2dcd5f2d4 ("media: v4l: async: Rename v4l2_async_subdev as v4l2_async_connection")

Signed-off-by: Robby Cai <robby.cai@nxp.com>